#!/bin/sh

search=${1:-lib}
echo Generating HTML Docs...

files=$(find $search \
         -name blib -prune \
      -o \( -name \*.pm -o -name \*.pod \) -type f -exec grep -l ^=head1 {} \; \
       | sed s,^$search/,,)

echo $files
test -d htdocs || mkdir htdocs
for x in $files
do
  echo $x...
  dir=$(dirname $x)
  file=$(basename $(basename $x .pod) .pm)
  up=$(dirname $x | sed 's,[a-zA-Z0-9_]\+,..,g')
  test -d htdocs/$dir || mkdir -p htdocs/$dir
  case $file
  in 
    *FAQ*)
      pod2html --podroot=$search --infile=$search/$x --htmlroot=$up --index >htdocs/$dir/$file.html
      ;;
    *)
      pod2html --podroot=$search --infile=$search/$x --htmlroot=$up --noindex >htdocs/$dir/$file.html
      ;;
  esac
done
rm -f pod2htm*
test -f htdocs/index.xml  && ./mkindex htdocs/index.xml

