#!/bin/sh

(
  for x in $(find . -type d)
  do
    if [ -f $x/CVS/Entries ]; then
      grep ^/ $x/CVS/Entries | cut -d/ -f2 | sed s,^,$x/, | sed s,^\./,,
    fi
  done
  find lib -name \*.pm
  find lib -name \*.pod
) | sort -u > MANIFEST.new
diff -u MANIFEST MANIFEST.new && rm MANIFEST.new
