name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: 5.10
          with-devel: true

  linux:
    name: "Perl ${{ matrix.perl-version }}"
    needs: [perl-versions]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          global: false
      - name: Set PERL5LIB to local lib
        run: echo "PERL5LIB=$(pwd)/local/lib/perl5" >> $GITHUB_ENV
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test
